# .rubocop.yml

# Target the Ruby version you are currently using
AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  # Exclude common folders that don't need linting
  Exclude:
    - "vendor/**/*"
    - "bin/*"
    - "db/schema.rb"

# 1. Enforce two-space indentation
Layout/IndentationConsistency:
  EnforcedStyle: normal

Layout/IndentationWidth:
  Width: 2

# 2. Enforce snake_case for variable names
Naming/VariableName:
  EnforcedStyle: snake_case

# 3. Disable: Missing frozen string literal comment
Style/FrozenStringLiteralComment:
  Enabled: false

# 4. Disable: Missing top-level documentation comment
Style/Documentation:
  Enabled: false

# Optional: Set a comfortable line length (default is 80)
Layout/LineLength:
  Max: 120
